### ISSUE TITLE
implement fromFingerprint

### ISSUE THREAD

**Issue by OR13** [mattrglobal/bls12381-key-pair#14]
needed for did key, here is an example:

https://github.com/transmute-industries/did-key.js/blob/master/packages/x25519/src/X25519KeyPair.ts#L64

**Comment by OR13** [comment]
Feel free to copy and paste: https://github.com/transmute-industries/did-key.js/blob/master/packages/bls12381/src/Bls12381G2KeyPair.ts#L4

although I do like that your implementation uses constants.

**Comment by tplooker** [comment]
Thanks, good addition, should the function signature be `fromFingerprint(fingerprint: string)` or `from({ fingerprint: string }: any)` as currently it appears to be doubling up on semantics i.e the call would be `const keyPair = Bls1238162.fromFingerprint ({ fingerprint : "z......." })`?

**Comment by OR13** [comment]
If should be like this: https://github.com/digitalbazaar/crypto-ld/blob/master/lib/LDKeyPair.js#L128

**Comment by OR13** [comment]
this function is in turn relied on in did-key.... like so:

https://github.com/digitalbazaar/did-method-key-js/blob/master/lib/driver.js#L43

**Comment by tplooker** [comment]
Ok we will adhere to this interface for now but will perhaps revisit it down the track because of the semantic double up explained above.

**Comment by OR13** [comment]
@tplooker We probably need an interface for LDKeyPair in TypeScript... open to collaboration on that.... 

I had similar challenges with this libraries use of buffers, and not leveraging base58btc... while I agree with what you are doing, I found the difference slightly frustrating.

a standard interface for these things would help us all :)

**Comment by tplooker** [comment]
@OR13 your implementation appears to not feed in the id and controller, instead it assumes they are did key, should the function signature be extended to be `const keyPair = Bls1238162.fromFingerprint ({ id: "did:key:z", controller: "did:key:.....", fingerprint : "z......." })` should I open an issue on the did key implementation?

**Comment by OR13** [comment]
AFAIK, did:key is the only consumer of that kind of fingerprint, and in my implementation it's assumed. I would not change the signature of that static method, because its basically meant to be the same as https://github.com/digitalbazaar/crypto-ld/blob/master/lib/LDKeyPair.js#L128

**Comment by tplooker** [comment]
Ok we will work with this interface for now and look to revisit it a little later on

**Comment by tplooker** [comment]
@OR13 this addition should be available in [v0.3.1-unstable.046a371](https://www.npmjs.com/package/@mattrglobal/bls12381-key-pair/v/0.3.1-unstable.046a371) we will roll a release in the next week or so once a few other changes have been made
