### ISSUE TITLE
generate should take entropy source or seed

### ISSUE THREAD

**Issue by OR13** [mattrglobal/bls12381-key-pair#30]
It would be nice to deterministically generate keys (say from mnemonics)...

In order to do this, the key generators need to take:

```
secureRandom: ()=> bytes
```

Which you can shim with a specific value if you want deterministic keys from a specific value.

**Comment by tplooker** [comment]
Hey @OR13 can you clarify, we already support deriving a key pair from a supplied seed? https://github.com/mattrglobal/bls12381-key-pair/blob/master/src/Bls12381G1KeyPair.ts#L176 so the only thing this library does not handle is converting say a mnemonic to the seed (a Uint8Array)

**Comment by OR13** [comment]
ahh nice, I can close this then... I must have missed that.
